version: "3"

services:
  postgres:
    image: postgres:14.1
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./.data/db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
