basePath: /api/v1
definitions:
  handler.APIError:
    properties:
      errorCode:
        type: integer
      errorMessage:
        type: string
    type: object
host: localhost:3000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /video:
    get:
      consumes:
      - application/json
      description: get all the videos with name and content
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: We need ID!!
          schema:
            $ref: '#/definitions/handler.APIError'
        "404":
          description: Can not find ID
          schema:
            $ref: '#/definitions/handler.APIError'
      summary: get all videos
      tags:
      - Video
    post:
      consumes:
      - application/json
      description: create a new video with name and content
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: We need ID!!
          schema:
            $ref: '#/definitions/handler.APIError'
        "404":
          description: Can not find ID
          schema:
            $ref: '#/definitions/handler.APIError'
      summary: create a new video
      tags:
      - Video
swagger: "2.0"
